language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs src --standard=psr2